framework:
    rate_limiter:
        registration_limiter:
            policy: sliding_window
            limit: 5
            interval: '3600 seconds'
            cache_pool: cache.app.dbal
        password_reset_limiter:
            policy: sliding_window
            limit: 5
            interval: '3600 seconds'
            cache_pool: cache.app.dbal
        resend_limiter:
            policy: sliding_window
            limit: 5
            interval: '3600 seconds'
            cache_pool: cache.app.dbal

when@test:
    framework:
        rate_limiter:
            registration_limiter:
                policy: sliding_window
                limit: 10000
                interval: '1 seconds'
                cache_pool: cache.app
