vich_uploader:
    db_driver: orm
    mappings:
        book_cover:
            uri_prefix: /uploads/books/covers
            upload_destination: '%kernel.project_dir%/public/uploads/books/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        book_gallery:
            uri_prefix: /uploads/books/gallery
            upload_destination: '%kernel.project_dir%/public/uploads/books/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
