name: app

type: php:8.3

build:
    flavor: composer

dependencies:
    nodejs:
        nvm: "*"

hooks:
    build: |
        set -e
        nvm use 20
        npm ci
        npm run build

relationships:
    database: "database:postgresql"

web:
    locations:
        /:
            root: "public"
            expires: 1h
            passthru: /index.php

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "public/uploads": { source: local, source_path: uploads }

variables:
    env:
        APP_ENV: prod
        APP_DEBUG: "0"
