name: app

type: php:8.3

build:
    flavor: composer

dependencies:
    nodejs:
        nvm: "*"

hooks:
    build: |
        set -e
        nvm use 20
        npm ci
        npm run build

relationships:
    database: "database:postgresql"

web:
    locations:
        /:
            root: "public"
            expires: 1h
            passthru: /index.php

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "public/uploads": { source: local, source_path: uploads }

workers:
    messenger:
        commands:
            start: php bin/console messenger:consume async --memory-limit=128M --time-limit=3600

crons:
    purge_activity_events:
        spec: "0 3 1 * *"
        cmd: "php bin/console app:purge-activity-events"

variables:
    env:
        APP_ENV: prod
        APP_DEBUG: "0"
