<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525200729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contribution (id UUID NOT NULL, role VARCHAR(20) NOT NULL, details VARCHAR(255) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contributor_id UUID NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA351E157A19A357 ON contribution (contributor_id)');
        $this->addSql('CREATE INDEX IDX_EA351E1516A2B381 ON contribution (book_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_contribution_contributor_book_role ON contribution (contributor_id, book_id, role)');
        $this->addSql('CREATE TABLE contributor (id UUID NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, pseudo VARCHAR(100) DEFAULT NULL, slug VARCHAR(255) NOT NULL, biography TEXT DEFAULT NULL, nationality VARCHAR(2) DEFAULT NULL, birth_date DATE DEFAULT NULL, death_date DATE DEFAULT NULL, portrait_image VARCHAR(255) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DA6F9793989D9B62 ON contributor (slug)');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E157A19A357 FOREIGN KEY (contributor_id) REFERENCES contributor (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E1516A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT fk_cbe5a3315370e40b');
        $this->addSql('DROP INDEX idx_cbe5a3315370e40b');
        $this->addSql('ALTER TABLE book ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE book DROP translator_id');
        $this->addSql('ALTER TABLE book_author DROP CONSTRAINT fk_9478d345f675f31b');
        $this->addSql('ALTER TABLE book_author DROP CONSTRAINT fk_9478d34516a2b381');
        $this->addSql('ALTER TABLE book_illustrator DROP CONSTRAINT fk_c5f85ecb653613b3');
        $this->addSql('ALTER TABLE book_illustrator DROP CONSTRAINT fk_c5f85ecb16a2b381');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE book_author');
        $this->addSql('DROP TABLE book_illustrator');
        $this->addSql('DROP TABLE illustrator');
        $this->addSql('DROP TABLE translator');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_bdafd8c8989d9b62 ON author (slug)');
        $this->addSql('CREATE TABLE book_author (book_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (book_id, author_id))');
        $this->addSql('CREATE INDEX idx_9478d34516a2b381 ON book_author (book_id)');
        $this->addSql('CREATE INDEX idx_9478d345f675f31b ON book_author (author_id)');
        $this->addSql('CREATE TABLE book_illustrator (book_id INT NOT NULL, illustrator_id INT NOT NULL, PRIMARY KEY (book_id, illustrator_id))');
        $this->addSql('CREATE INDEX idx_c5f85ecb16a2b381 ON book_illustrator (book_id)');
        $this->addSql('CREATE INDEX idx_c5f85ecb653613b3 ON book_illustrator (illustrator_id)');
        $this->addSql('CREATE TABLE illustrator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_970f11b7989d9b62 ON illustrator (slug)');
        $this->addSql('CREATE TABLE translator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_58cde3eb989d9b62 ON translator (slug)');
        $this->addSql('ALTER TABLE book_author ADD CONSTRAINT fk_9478d345f675f31b FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_author ADD CONSTRAINT fk_9478d34516a2b381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_illustrator ADD CONSTRAINT fk_c5f85ecb653613b3 FOREIGN KEY (illustrator_id) REFERENCES illustrator (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_illustrator ADD CONSTRAINT fk_c5f85ecb16a2b381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contribution DROP CONSTRAINT FK_EA351E157A19A357');
        $this->addSql('ALTER TABLE contribution DROP CONSTRAINT FK_EA351E1516A2B381');
        $this->addSql('DROP TABLE contribution');
        $this->addSql('DROP TABLE contributor');
        $this->addSql('ALTER TABLE book ADD translator_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE book DROP deleted_at');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT fk_cbe5a3315370e40b FOREIGN KEY (translator_id) REFERENCES translator (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_cbe5a3315370e40b ON book (translator_id)');
    }
}
