<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601091426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE collection_publishing_history (id UUID NOT NULL, start_year SMALLINT NOT NULL, end_year SMALLINT DEFAULT NULL, edition_name VARCHAR(255) DEFAULT NULL, details TEXT DEFAULT NULL, collection_id UUID NOT NULL, editor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF0997D5514956FD ON collection_publishing_history (collection_id)');
        $this->addSql('CREATE INDEX IDX_EF0997D56995AC4C ON collection_publishing_history (editor_id)');
        $this->addSql('CREATE INDEX idx_cph_collection_year_id ON collection_publishing_history (collection_id, start_year, id)');
        $this->addSql('ALTER TABLE collection_publishing_history ADD CONSTRAINT FK_EF0997D5514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection_publishing_history ADD CONSTRAINT FK_EF0997D56995AC4C FOREIGN KEY (editor_id) REFERENCES editor (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contributor_level ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contributor_level ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_contributor_level_rank_number RENAME TO UNIQ_B5DE8D11803F4E2');
        $this->addSql('ALTER TABLE email_verification_token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE email_verification_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN email_verification_token.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN email_verification_token.created_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_email_verification_token_token RENAME TO UNIQ_C4995C675F37A13B');
        $this->addSql('ALTER INDEX uniq_email_verification_token_user RENAME TO UNIQ_C4995C67A76ED395');
        $this->addSql('ALTER TABLE reset_password_token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reset_password_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_token.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_token.created_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_reset_password_token_token RENAME TO UNIQ_452C9EC55F37A13B');
        $this->addSql('COMMENT ON COLUMN suggestion.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion.source_entity_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion.submitted_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.suggestion_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.moderator_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.refused_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_suggestion_refusal_suggestion RENAME TO UNIQ_F5BEB03EA41BB822');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE collection_publishing_history DROP CONSTRAINT FK_EF0997D5514956FD');
        $this->addSql('ALTER TABLE collection_publishing_history DROP CONSTRAINT FK_EF0997D56995AC4C');
        $this->addSql('DROP TABLE collection_publishing_history');
        $this->addSql('ALTER TABLE contributor_level ALTER id SET DEFAULT nextval(\'contributor_level_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE contributor_level ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_b5de8d11803f4e2 RENAME TO uniq_contributor_level_rank_number');
        $this->addSql('ALTER TABLE email_verification_token ALTER id SET DEFAULT nextval(\'email_verification_token_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE email_verification_token ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN email_verification_token.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN email_verification_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_c4995c67a76ed395 RENAME TO uniq_email_verification_token_user');
        $this->addSql('ALTER INDEX uniq_c4995c675f37a13b RENAME TO uniq_email_verification_token_token');
        $this->addSql('ALTER TABLE reset_password_token ALTER id SET DEFAULT nextval(\'reset_password_token_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reset_password_token ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_token.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_452c9ec55f37a13b RENAME TO uniq_reset_password_token_token');
        $this->addSql('COMMENT ON COLUMN suggestion.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN suggestion.source_entity_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN suggestion.submitted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN suggestion.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.refused_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.suggestion_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN suggestion_refusal.moderator_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER INDEX uniq_f5beb03ea41bb822 RENAME TO uniq_suggestion_refusal_suggestion');
    }
}
