<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525083803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDAFD8C8989D9B62 ON author (slug)');
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, original_title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, isbn VARCHAR(20) DEFAULT NULL, pages INT DEFAULT NULL, paragraphs INT DEFAULT NULL, french_publication_year SMALLINT DEFAULT NULL, original_publication_year SMALLINT DEFAULT NULL, edition_info VARCHAR(255) DEFAULT NULL, saga VARCHAR(255) DEFAULT NULL, volume_number SMALLINT DEFAULT NULL, summary TEXT DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, languages JSON NOT NULL, translator_id INT DEFAULT NULL, editor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBE5A331989D9B62 ON book (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBE5A331CC1CF4E6 ON book (isbn)');
        $this->addSql('CREATE INDEX IDX_CBE5A3315370E40B ON book (translator_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A3316995AC4C ON book (editor_id)');
        $this->addSql('CREATE INDEX idx_book_slug ON book (slug)');
        $this->addSql('CREATE INDEX idx_book_status ON book (status)');
        $this->addSql('CREATE TABLE book_author (book_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (book_id, author_id))');
        $this->addSql('CREATE INDEX IDX_9478D34516A2B381 ON book_author (book_id)');
        $this->addSql('CREATE INDEX IDX_9478D345F675F31B ON book_author (author_id)');
        $this->addSql('CREATE TABLE book_illustrator (book_id INT NOT NULL, illustrator_id INT NOT NULL, PRIMARY KEY (book_id, illustrator_id))');
        $this->addSql('CREATE INDEX IDX_C5F85ECB16A2B381 ON book_illustrator (book_id)');
        $this->addSql('CREATE INDEX IDX_C5F85ECB653613B3 ON book_illustrator (illustrator_id)');
        $this->addSql('CREATE TABLE book_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tab VARCHAR(20) NOT NULL, image_path VARCHAR(255) NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBFF112616A2B381 ON book_image (book_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_book_tab ON book_image (book_id, tab)');
        $this->addSql('CREATE TABLE editor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CCF1F1BA989D9B62 ON editor (slug)');
        $this->addSql('CREATE TABLE illustrator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_970F11B7989D9B62 ON illustrator (slug)');
        $this->addSql('CREATE TABLE translator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58CDE3EB989D9B62 ON translator (slug)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3315370E40B FOREIGN KEY (translator_id) REFERENCES translator (id)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3316995AC4C FOREIGN KEY (editor_id) REFERENCES editor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_author ADD CONSTRAINT FK_9478D34516A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_author ADD CONSTRAINT FK_9478D345F675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_illustrator ADD CONSTRAINT FK_C5F85ECB16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_illustrator ADD CONSTRAINT FK_C5F85ECB653613B3 FOREIGN KEY (illustrator_id) REFERENCES illustrator (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_image ADD CONSTRAINT FK_CBFF112616A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE correction_proposal DROP CONSTRAINT fk_correction_proposal_work_entry');
        $this->addSql('ALTER TABLE correction_proposal DROP CONSTRAINT fk_correction_proposal_author');
        $this->addSql('ALTER TABLE work_entry DROP CONSTRAINT fk_work_entry_author');
        $this->addSql('DROP TABLE correction_proposal');
        $this->addSql('DROP TABLE moderation_log');
        $this->addSql('DROP TABLE work_entry');
        $this->addSql('ALTER TABLE "user" DROP status');
        $this->addSql('ALTER TABLE "user" DROP deleted_at');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_8d93d649f5d16e51 RENAME TO UNIQ_8D93D64986CC499D');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE correction_proposal (id UUID NOT NULL, work_entry_id UUID NOT NULL, author_id UUID DEFAULT NULL, proposed_content JSON NOT NULL, status VARCHAR(10) DEFAULT \'PENDING\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DEB5F39C6F83C31E ON correction_proposal (work_entry_id)');
        $this->addSql('CREATE INDEX IDX_DEB5F39CF675F31B ON correction_proposal (author_id)');
        $this->addSql('COMMENT ON COLUMN correction_proposal.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN correction_proposal.work_entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN correction_proposal.author_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN correction_proposal.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE moderation_log (id UUID NOT NULL, moderator_id VARCHAR(36) NOT NULL, action_type VARCHAR(10) NOT NULL, target_entity_type VARCHAR(100) NOT NULL, target_entity_id VARCHAR(36) NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN moderation_log.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN moderation_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE work_entry (id UUID NOT NULL, author_id UUID DEFAULT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(10) DEFAULT \'PENDING\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DAE65FF675F31B ON work_entry (author_id)');
        $this->addSql('COMMENT ON COLUMN work_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN work_entry.author_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN work_entry.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE correction_proposal ADD CONSTRAINT fk_correction_proposal_work_entry FOREIGN KEY (work_entry_id) REFERENCES work_entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correction_proposal ADD CONSTRAINT fk_correction_proposal_author FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE work_entry ADD CONSTRAINT fk_work_entry_author FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3315370E40B');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3316995AC4C');
        $this->addSql('ALTER TABLE book_author DROP CONSTRAINT FK_9478D34516A2B381');
        $this->addSql('ALTER TABLE book_author DROP CONSTRAINT FK_9478D345F675F31B');
        $this->addSql('ALTER TABLE book_illustrator DROP CONSTRAINT FK_C5F85ECB16A2B381');
        $this->addSql('ALTER TABLE book_illustrator DROP CONSTRAINT FK_C5F85ECB653613B3');
        $this->addSql('ALTER TABLE book_image DROP CONSTRAINT FK_CBFF112616A2B381');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE book_author');
        $this->addSql('DROP TABLE book_illustrator');
        $this->addSql('DROP TABLE book_image');
        $this->addSql('DROP TABLE editor');
        $this->addSql('DROP TABLE illustrator');
        $this->addSql('DROP TABLE translator');
        $this->addSql('ALTER TABLE "user" ADD status VARCHAR(10) DEFAULT \'active\' NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN "user".deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_8d93d64986cc499d RENAME TO uniq_8d93d649f5d16e51');
    }
}
