<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609142803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".previous_login_at IS \'\'');
        $this->addSql('ALTER TABLE activity_event ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE activity_event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN activity_event.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN book.updated_at IS \'\'');
        $this->addSql('ALTER TABLE notification ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notification ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN notification.created_at IS \'\'');
        $this->addSql('ALTER TABLE notification_preference ADD contribution_refused BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE notification_preference ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notification_preference ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_notification_preference_user RENAME TO UNIQ_A61B1571A76ED395');
        $this->addSql('ALTER TABLE user_book ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_book.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_book.updated_at IS \'\'');
        $this->addSql('ALTER TABLE user_collection_subscription ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_collection_subscription ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_collection_subscription.created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_event ALTER id SET DEFAULT nextval(\'activity_event_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE activity_event ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN activity_event.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN book.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE notification ALTER id SET DEFAULT nextval(\'notification_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notification ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN notification.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE notification_preference DROP contribution_refused');
        $this->addSql('ALTER TABLE notification_preference ALTER id SET DEFAULT nextval(\'notification_preference_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notification_preference ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_a61b1571a76ed395 RENAME TO uniq_notification_preference_user');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".previous_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user_book ALTER id SET DEFAULT nextval(\'user_book_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE user_book ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_book.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_book.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user_collection_subscription ALTER id SET DEFAULT nextval(\'user_collection_subscription_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE user_collection_subscription ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_collection_subscription.created_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
